replicaCount: 1
image:
  repository: zahraehghaghi/python-app1
  pullPolicy: IfNotPresent
  tag: a5a0a8
imagePullSecrets: []
nameOverride: "python-app1"
fullnameOverride: "python-app1"
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels:
  app: python-app1
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: python-app1-prod.test.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
